version: '2'

volumes:
  phabricator-storage:
      driver: local
  phabricator-repository:
      driver: local

networks:
  phabricator:

services:
  phabricator-mariadb:
    container_name: phabricator-mariadb
    image: veeenex/phabricator-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: phabricator
      MYSQL_USER: phabricator
      MYSQL_PASSWORD: phabricator
      MYSQL_DATABASE: phabricator
    networks:
      - phabricator

  phabricator:
    container_name: phabricator
    image: veeenex/phabricator
    restart: always
    volumes:
      - phabricator-storage:/var/storage
      - phabricator-repository:/var/repo
    ports:
      - 2222:2222
      - 22280:22280
    depends_on:
      - phabricator-mariadb
    networks:
      - phabricator

  phabricator-webserver:
    container_name: phabricator-webserver
    image: veeenex/phabricator-webserver
    restart: always
    volumes_from:
      - phabricator
    networks:
      - phabricator
    environment:
      VIRTUAL_HOST: "phabricator.dev"
