version: '2'

volumes:
  phabricator-storage:
  phabricator-repository:
  phabricator-mariadb:

networks:
  phabricator:

services:
  phabricator-mariadb:
    container_name: phabricator-mariadb
    build: docker/phabricator-mariadb
    volumes:
      - phabricator-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: phabricator
      MYSQL_USER: phabricator
      MYSQL_PASSWORD: phabricator
      MYSQL_DATABASE: phabricator
    networks:
      - phabricator

  phabricator:
    container_name: phabricator
    build:
      context: docker/phabricator
      args:
        MYSQL_HOST: phabricator-mariadb
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: phabricator
    volumes:
      - phabricator-storage:/var/storage
      - phabricator-repository:/var/repo
    ports:
      - 2222:2222
      - 22280:22280
    depends_on:
      - phabricator-mariadb
    networks:
      - phabricator

  phabricator-webserver:
    container_name: phabricator-webserver
    build: docker/phabricator-webserver
    volumes_from:
      - phabricator
    networks:
      - phabricator
    environment:
      VIRTUAL_HOST: "phabricator.dev"
